---

- name: manage resolving
  include_tasks: resolv.yml

- name: manage packages
  include_tasks: packages.yml

- name: install opensource vmware tools
  include_tasks: open-vmware-tools.yml
  when: install_open_vmware_tools

- name: configure system
  include_tasks: system.yml

- name: manage root user setting
  include_tasks: root.yml

- name: manage users
  include_tasks: users.yml
  when: add_users

- name: prepare system
  include_tasks: sysprep.yml

...
