---

- name: install epel-release
  yum: name=epel-release state=latest

- name: update system
  yum: name=* state=latest

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ install_packages }}"

...
