---
- name: install epel-release
  yum: name=epel-release state=latest

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - telnet
    - nmap
    - bind-utils
    - htop
    - salt-minion
    - pigz
    - wget
    - git
    - whois
    - sudo

- name: clean yum cache
  file:
    state: absent
    path: /var/cache/yum
...
