---
- name: chattr resolv file
  file:
    path: /etc/resolv.conf
    attributes: e

- name: modify resolv file
  template:
    src: templates/resolv.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: u+rw,g+r,o+r
#    attributes: e
- name: chattr resolv file
  file:
    path: /etc/resolv.conf
    attributes: ie    
