---

- name: set up root password
  user:
    name: root
    update_password: always
    password: "{{ root_passwd }}"

- name: import ssh-keys for root user
  authorized_key:
    exclusive: yes
    key: "{{ root_ssh_keys }}"
    state: present
    user: "root"

...
