---

- name: remove old kernels
  shell: $( which package-cleanup ) --oldkernels --count=1 -y

- name: find ssh hostkey to force generation after reboot
  find:
    paths: "/etc/ssh"
    recurce: "no"
    use_regex: no
    patterns: "^ssh_host_"
    hidden: no
    file_type: file
  register: var_ssh_hostkey

- name: remove ssh hostkey to force generation after reboot
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ var_ssh_hostkey.files|default([]) }}"
  when: var_ssh_hostkey

- name: stop logging on server
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - "rsyslog.service"
    - "systemd-journald.service"
    - "systemd-journald.socket"

- name: find journal files
  find:
    paths: "/var/log/journal"
    recurce: "yes"
    hidden: yes
  register: journal_files

- name: remove journal files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ journal_files.files|default([]) }}"
  when: journal_files

- name: find rotated logs and archives
  find:
    paths: "/var/log"
    recurce: "yes"
    use_regex: no
    patterns: '*-2*,*.gz'
    hidden: yes
    file_type: file
  register: gzipped_logs

- name: remove rotated logs and archives
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ gzipped_logs.files|default([]) }}"
  when: gzipped_logs

- name: clean yum cache
  file:
    state: absent
    path: /var/cache/yum

...
